config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
  @contact = Contact.new(contact_params)

  if @contact.save
    redirect_to contacts_path
  else
    render :new
  end
end
def update
  @contact = Contact.find(params[:id])

  if @contact.update(contact_params)
    redirect_to contact_path
  else
    render :edit
  end
end
def destroy
  Contact.find(params[:id]).destroy
  redirect_to contacts_path
end

private

  def contact_params
    params.require(:contact).permit(:name, :age, :gender, :hair_color, :eye_color, :alive)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def home
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Edit a Contact</h1>
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>
<% end %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<button><%= link_to 'New Contact', new_contact_path %></button>
<% @contacts.each do |contact| %>
  <h5><%= contact.name %></h5>
  <button><%= link_to 'View', contact_path(contact) %></button>
  <button><%= link_to 'Edit', edit_contact_path(contact) %></button>
  <button><%= link_to 'Delete', contact, method: :delete %></button>
<% end %>

app/views/contacts/new.html.erb
<h1>Create a New Contact</h1>
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>
<% end %>

app/views/contacts/show.html.erb
<h1>Name: <%= @contact.name %> </h1>
<p>Age: <%= @contact.age %></p>
<p>Gender: <%= @contact.gender %></p>
<p>Hair Color: <%= @contact.hair_color %></p>
<p>Eye Color: <%= @contact.eye_color %></p>
<p>Alive: <%= @contact.alive %></p>
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<nav>
   <div class="nav-wrapper indigo darken-2">
     <a href="/contacts" class="brand-logo">Contacts</a>
     <ul id="nav-mobile" class="right hide-on-med-and-down">
       <li><a href="/contacts/new">New Contact</a></li>

     </ul>
   </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Contacts</title>

  </head>
  <body>
    <h1>welcome to the Contacts list</h1>

  </body>
</html>